name: "Self Delete Workflow"
description: "An action that deletes the workflow that launches it"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Workflow Path
      id: get_workflow_path
      shell: bash
      run: |
        IFS='@'
        read -a strarr <<< "$GITHUB_WORKFLOW_REF"
        workflow_ref=${strarr[0]}
        workflow_path=${workflow_ref#"$GITHUB_REPOSITORY/"}
        
        echo "value=$workflow_path" >> $GITHUB_OUTPUT
    - name: Delete Workflow
      shell: bash
      run: |
        rm '${{ steps.get_workflow_path.outputs.value }}'
    - name: Config git
      shell: bash
      run: |
        git config user.name "Self Delete Workflow Github Action"
        git config user.email "<>"
    - name: Commit the changes to the current branch
      shell: bash
      run: |
        git show
        git add --all
        git commit -m "chore: remove the delete-tags-without-release workflow"
        git show
        


