name: "Self Delete Workflow"
description: "An action that deletes the workflow that launches it"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Workflow Path
      id: get_workflow_path
      shell: bash
      run: |
        IFS='@'
        read -a strarr <<< "$GITHUB_WORKFLOW_REF"
        workflow_ref=${strarr[0]}
        workflow_path=${workflow_ref#"$GITHUB_REPOSITORY/"}
        
        echo "value=$workflow_path" >> $GITHUB_OUTPUT
    - name: Delete Workflow
      shell: bash
      run: |
        rm '${{ steps.get_workflow_path.outputs.value }}'
    - name: Config git user
      shell: bash
      run: |
        git config user.name "Self Delete Workflow Github Action"
        git config user.email "<>"
    - name: Create and checkout a new temporary branch
      id: temp_branch
      shell: bash
      run: |
        TEMP_BRANCH_NAME=self_delete_${{ github.run_id }}-${{ github.run_attempt }}
        git checkout -b $TEMP_BRANCH_NAME
        echo "value=$TEMP_BRANCH_NAME" >> $GITHUB_OUTPUT
    - name: Build the commit message
      id: commit_message
      shell: bash
      run: |
        COMMIT_MESSAGE="chore: remove the ${{ steps.get_workflow_path.outputs.value }} workflow"
        echo "value=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
    - name: Commit and push the changes to the temporary branch
      shell: bash
      run: |
        git add --all
        git commit -m "${{ steps.commit_message.outputs.value }}"
        git push -u origin ${{ steps.temp_branch.outputs.value }}
    - name: Push changes to the branch that triggered the workflow (even if its protected)
      shell: bash
      run: |
        gh pr create --base ${{ github.ref_name }} --head self_delete --title "${{ steps.commit_message.outputs.value }}" --body "This Pull Request has been created by the **Push to Pull Request protected branch** Github Action"
        gh pr merge --auto --delete-branch --squash
        


