name: "Self Delete Workflow"
description: "An action that deletes the workflow that launches it"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Remove Workflow Folder
      shell: bash
      run: |
        echo $GITHUB_WORKFLOW_REF

