name: "Self Delete Workflow"
description: "An action that deletes the workflow that launches it"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Remove Workflow Folder
      shell: bash
      run: |
        IFS='@'
        read -a strarr <<< "$GITHUB_WORKFLOW_REF"
        workflow_ref=${strarr[0]}
        workflow_dir=${workflow_ref#"$GITHUB_REPOSITORY"}
        
        echo $workflow_dir

